spring:
  application:
    name: quad-management
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET:mySuperSecureJWTKeyThatIsAtLeast32BytesLong123andImgonnamakesureitsevenlongerIamtypingjustforthesakeoftyping123456Ihopeitmadeit234567!}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  file:
    name: myapp.log

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration